name: Notificar Microsoft Teams

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, closed]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Enviar notificação para Microsoft Teams
        uses: Ilshidur/action-slack@v1.3.0
        with:
          webhook-url: ${{ secrets.TEAMS_WEBHOOK_URL }}
          msg: |
            Notificação do GitHub:
            - Evento: ${{ github.event_name }}
            - Repositório: ${{ github.repository }}
            - Autor: ${{ github.actor }}
