name: Notificar Microsoft Teams

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, closed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar notificação para Microsoft Teams
        uses: atlassian/gajira-notify@master
        with:
          url: ${{ secrets.TEAMS_WEBHOOK_URL }}
          message: "Novo evento no GitHub: ${{ github.event_name }} no repositório ${{ github.repository }}"
